/*
 * oas3_go_flutter_exam Employee
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Employee struct {

	Id string `json:"id"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	Salary int64 `json:"salary"`
}
